### ISSUE TITLE
Roadmap: Atlantis 0.2.0 (proposal)

### ISSUE THREAD

**Issue by anubhavmishra** [hootsuite/atlantis#173]
- [x] Investigate VCS support for Bitbucket, Gitlab, gogs and gitea ( GH #174 )
- [ ] Plan on push ( GH #165 )
- [ ] Apply on merge ( GH #162 )
- [ ] Improve e2e tests ( GH #71 )

**Comment by anubhavmishra** [comment]
@lkysow Please feel free to add to this. Let's get this ironed out for the next major release.

**Comment by lkysow** [comment]
0.2.0 was released with GitLab and Slack. I think we can use milestones to track future releases rather than specific tickets.
